### ISSUE TITLE
Ensure Sandbox resources are always deleted from Azure after Sandbox is deleted from Sepes 

### ISSUE THREAD

**Issue by krsteen** [equinor/sepes-api#324] opened 2020-10-12 08:35 UTC
NOTE: This problem will be adressed in #343 

Kristoffer has seen that sometimes azure resources are not deleted properly. need tests/monitoring to ensure it happens

Visit sepes (any env)
Select or Create a Study
Select or Create a Sandbox
Optional: Wait for sandbox creation to complete (unsure if this is relevant for reproducing)
Delete the Sandbox
Sandbox is deleted from Sepes and one is redirected to the Study page
Vist Azure portal after a while (10 mins) and notice that relevant resource group is not deleted
When visiting Activity Log for the resource group, one might find a "Delete resource group" there, but it's not carried through

**Theories:**
I suspect this might might only happen when one is deleting a Sandbox while it's under construction, so since Sepes is setting up a Azure resource at the time, the delete operation is blocked. 
Especially if the Sandbox is deleted while Sepes  is creating a Bastion, which is a long running task that might collide with the delete operation

**Actions to take regardless**
We should add additional fields to SandboxResources: 
We currently have "Deleted and DeletedBy", we should add "Marked for deletion" and "MarkedForDeletionBy"
We can also just use the operations-table for this: A  Resource is marked for deletion if is a unfinished "Delete" operation, and "Really deleted" when this operation is completed
We need a way for Sepes to ensure resource is actually deleted, and that Sepes keeps tryng further before giving up. It should also notify some admins if deletion failed

**Questions:**
When a Sandbox is deleted, maybe it can still be visible until it has been fully deleted (All Azure resources deleted) to those wo know the Id. So the user is not redirected away from the page, but can pay attention to the Resources being deleted.

**Comment by einaren** [comment] 2020-12-03 12:21
See if we can make a test that tries to recreate the problem

**Comment by einaren** [comment] 2021-04-08 11:06
Closing this as it is a duplicate of #343

**Closed as completed by einaren** 2021-04-08 11:06 UTC
Labels: Bug, Backend, azure
