### ISSUE TITLE
Review access_control.md

### ISSUE THREAD

**Issue by krsteen** [equinor/sepes-api#314] opened 2020-10-08 10:21 UTC
Document can be found here: https://github.com/equinor/sepes-web/blob/master/docs/access_control.md

**Actions:**
View all unrestricted studies: All equinor users can do this
New Action: Reassign owner?

Missing actions:

**Roles**
Study Owner (the one that created the study)
If Admin should not be allowed to view ALL studies, should we have a Developer Role?
Missing roles: Study owner

**Comment by krsteen** [comment] 2020-10-08 10:25
Document can be found at https://github.com/equinor/sepes-web/blob/master/docs/access_control.md

**Comment by einaren** [comment] 2020-11-26 12:18
Duplicate of equinor/sepes-internal/#7

**Closed by einaren** 2020-11-26 12:18 UTC
Labels: Backend, Documentation, petter
